[package]
name = "Chip8InRust"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.25"
rand = "0.9.0"
rand_chacha = "0.9.0"
